version: '3'
services: 
  api:
    build: 
# Java API version 
      context: ../back-end-java
# scala API version 
#	   context: ../back-end-scala
      dockerfile: Dockerfile
    image: api:0.0.1
    ports:
      - "8080:8080"
  web:
    build:
      context: ../front-end 
      dockerfile: Dockerfile
    image: web:0.0.1
    ports:
      - "4200:4200"